---
- hosts: all
  remote_user: vagrant
  sudo: yes
  tasks:
  - apt: update_cache=yes upgrade=full

  - apt: name={{item}} state=latest
    with_items:
      - python-dev
      - python-pip
      - gitolite3
      - sqlite3

  - pip: chdir=/vagrant
         requirements=/vagrant/requirements_dev.txt

  - command: gitolite setup -a djangit
    sudo_user: vagrant

  - django_manage: app_path=/vagrant/djangit_project/
                   command=migrate
